# These are supported funding model platforms

github: [xledocteurx]
patreon: lenoirc
open_collective: soundcase
ko_fi: soundcase
# tidelift: npm/soundcase
paypal: xledocteurx
custom: https://paypal.me/xledocteurx
